import streamlit as st
import pickle
import json
import os
from greentensor.report.metrics import RunMetrics, calculate_savings

st.set_page_config(page_title="GreenTensor Dashboard", page_icon="🌿")
st.title("GreenTensor Impact Dashboard")
st.caption("Carbon-aware MLOps monitoring — by Dhivya Balakumar")

# ── Sidebar ───────────────────────────────────────────────────────────────────
st.sidebar.header("Data Source")
mode = st.sidebar.radio("Input mode", ["Manual", "Upload File"])

st.sidebar.markdown("---")
st.sidebar.markdown("**File formats accepted:**")
st.sidebar.markdown("- `.pkl` — auto-generated by `train_baseline.py`")
st.sidebar.markdown("- `.json` — create manually (see format below)")

baseline_metrics = None
optimized_metrics = None

# ── Helper ────────────────────────────────────────────────────────────────────
def load_metrics(file) -> RunMetrics:
    """Load a RunMetrics from a .pkl or .json file."""
    name = file.name.lower()
    if name.endswith(".pkl"):
        return pickle.load(file)
    elif name.endswith(".json"):
        data = json.load(file)
        return RunMetrics(
            duration_s=float(data["duration_s"]),
            energy_kwh=float(data["energy_kwh"]),
            emissions_kg=float(data["emissions_kg"]),
            idle_seconds=float(data.get("idle_seconds", 0.0)),
        )
    else:
        st.error(f"Unsupported file type: {name}")
        return None

# ── Input modes ───────────────────────────────────────────────────────────────
if mode == "Manual":
    st.subheader("Manual Input")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Baseline run (no optimizations)**")
        b_energy    = st.number_input("Energy (kWh)",       key="b_e",  min_value=0.0, format="%.6f")
        b_emissions = st.number_input("Emissions (kg CO2)", key="b_em", min_value=0.0, format="%.6f")
        b_duration  = st.number_input("Duration (s)",       key="b_d",  min_value=0.0)
    with col2:
        st.markdown("**Optimized run (with GreenTensor)**")
        o_energy    = st.number_input("Energy (kWh)",       key="o_e",  min_value=0.0, format="%.6f")
        o_emissions = st.number_input("Emissions (kg CO2)", key="o_em", min_value=0.0, format="%.6f")
        o_duration  = st.number_input("Duration (s)",       key="o_d",  min_value=0.0)

    if b_energy > 0 and o_energy > 0:
        baseline_metrics  = RunMetrics(duration_s=b_duration,  energy_kwh=b_energy,  emissions_kg=b_emissions)
        optimized_metrics = RunMetrics(duration_s=o_duration,  energy_kwh=o_energy,  emissions_kg=o_emissions)

else:
    st.subheader("Upload Metrics Files")

    with st.expander("What file format should I use?"):
        st.markdown("""
**Option 1 — Auto-generated `.pkl`**

Run the example scripts and they save the file automatically:
```bash
python examples/train_baseline.py   # saves baseline_metrics.pkl
python examples/train_optimized.py  # saves optimized_metrics.pkl
```
Then upload those `.pkl` files here.

---

**Option 2 — Manual `.json`**

Create a JSON file with these fields:
```json
{
    "duration_s": 45.2,
    "energy_kwh": 0.000412,
    "emissions_kg": 0.000096,
    "idle_seconds": 2.1
}
```

Fields explained:
- `duration_s` — how long the training run took in seconds
- `energy_kwh` — total energy consumed in kilowatt-hours
- `emissions_kg` — CO2 emissions in kilograms
- `idle_seconds` — time GPU was idle (optional, defaults to 0)
        """)

    col1, col2 = st.columns(2)
    with col1:
        b_file = st.file_uploader("Baseline metrics (.pkl or .json)", type=["pkl", "json"], key="b_f")
        if b_file:
            baseline_metrics = load_metrics(b_file)
            if baseline_metrics:
                st.success("Baseline loaded.")
                st.json({
                    "duration_s": baseline_metrics.duration_s,
                    "energy_kwh": baseline_metrics.energy_kwh,
                    "emissions_kg": baseline_metrics.emissions_kg,
                    "idle_seconds": baseline_metrics.idle_seconds,
                })

    with col2:
        o_file = st.file_uploader("Optimized metrics (.pkl or .json)", type=["pkl", "json"], key="o_f")
        if o_file:
            optimized_metrics = load_metrics(o_file)
            if optimized_metrics:
                st.success("Optimized loaded.")
                st.json({
                    "duration_s": optimized_metrics.duration_s,
                    "energy_kwh": optimized_metrics.energy_kwh,
                    "emissions_kg": optimized_metrics.emissions_kg,
                    "idle_seconds": optimized_metrics.idle_seconds,
                })

    # Auto-load from disk if running locally
    if not baseline_metrics and os.path.exists("baseline_metrics.pkl"):
        with open("baseline_metrics.pkl", "rb") as f:
            baseline_metrics = pickle.load(f)
        st.info("Auto-loaded baseline_metrics.pkl from disk.")

# ── Results ───────────────────────────────────────────────────────────────────
if baseline_metrics and optimized_metrics:
    savings = calculate_savings(baseline_metrics, optimized_metrics)

    st.subheader("Results")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Energy Reduction",  f"{savings['energy_reduction_pct']:.1f}%")
    c2.metric("Energy Saved",      f"{savings['energy_saved_kwh']:.6f} kWh")
    c3.metric("CO2 Saved",         f"{savings['emissions_saved_kg']:.6f} kg")
    c4.metric("Time Saved",        f"{savings['time_saved_s']:.2f} s")

    st.subheader("Energy Comparison")
    st.bar_chart({
        "Baseline":  baseline_metrics.energy_kwh,
        "Optimized": optimized_metrics.energy_kwh,
    })

    st.subheader("Emissions Comparison")
    st.bar_chart({
        "Baseline":  baseline_metrics.emissions_kg,
        "Optimized": optimized_metrics.emissions_kg,
    })

elif baseline_metrics:
    st.subheader("Baseline Run")
    c1, c2, c3 = st.columns(3)
    c1.metric("Energy",    f"{baseline_metrics.energy_kwh:.6f} kWh")
    c2.metric("Emissions", f"{baseline_metrics.emissions_kg:.6f} kg CO2")
    c3.metric("Duration",  f"{baseline_metrics.duration_s:.2f} s")
    st.info("Upload or enter optimized metrics to see savings comparison.")
