import streamlit as st
import pickle
import json
import os
import pandas as pd
from greentensor.report.metrics import RunMetrics, calculate_savings

st.set_page_config(
    page_title="GreenTensor Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Global styles ─────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    .metric-card {
        background: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 6px;
        padding: 1.2rem 1.5rem;
        margin-bottom: 0.5rem;
    }
    .metric-label { font-size: 0.78rem; color: #6c757d; text-transform: uppercase; letter-spacing: 0.05em; }
    .metric-value { font-size: 1.6rem; font-weight: 700; color: #212529; }
    .metric-delta-good { font-size: 0.85rem; color: #198754; font-weight: 600; }
    .metric-delta-bad  { font-size: 0.85rem; color: #dc3545; font-weight: 600; }
    .section-title { font-size: 1.1rem; font-weight: 700; color: #212529;
                     border-bottom: 2px solid #dee2e6; padding-bottom: 0.4rem; margin-bottom: 1rem; }
    .alert-critical { background:#fff5f5; border-left:4px solid #dc3545; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-high     { background:#fff8f0; border-left:4px solid #fd7e14; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-medium   { background:#fffdf0; border-left:4px solid #ffc107; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-low      { background:#f0fff4; border-left:4px solid #198754; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .tag { display:inline-block; padding:0.15rem 0.5rem; border-radius:3px;
           font-size:0.72rem; font-weight:700; letter-spacing:0.04em; margin-right:0.3rem; }
    .tag-source { background:#e9ecef; color:#495057; }
    .tag-type   { background:#cfe2ff; color:#084298; }
    .clean-badge { background:#d1e7dd; color:#0a3622; padding:0.4rem 1rem;
                   border-radius:4px; font-weight:600; display:inline-block; }
    .threat-badge { background:#f8d7da; color:#58151c; padding:0.4rem 1rem;
                    border-radius:4px; font-weight:600; display:inline-block; }
    hr { border: none; border-top: 1px solid #dee2e6; margin: 1.5rem 0; }
</style>
""", unsafe_allow_html=True)


# ── Helpers ───────────────────────────────────────────────────────────────────
def metric_card(label, value, delta=None, delta_good=True):
    delta_html = ""
    if delta:
        cls = "metric-delta-good" if delta_good else "metric-delta-bad"
        delta_html = f'<div class="{cls}">{delta}</div>'
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-label">{label}</div>
        <div class="metric-value">{value}</div>
        {delta_html}
    </div>""", unsafe_allow_html=True)


def load_metrics_file(file) -> RunMetrics:
    """
    Accepts .pkl (binary, auto-generated by GreenTensor) or
    .json (human-readable, manually created).
    Returns a RunMetrics dataclass.
    """
    name = file.name.lower()
    if name.endswith(".pkl"):
        return pickle.load(file)
    elif name.endswith(".json"):
        data = json.load(file)
        return RunMetrics(
            duration_s=float(data["duration_s"]),
            energy_kwh=float(data["energy_kwh"]),
            emissions_kg=float(data["emissions_kg"]),
            idle_seconds=float(data.get("idle_seconds", 0.0)),
        )
    else:
        st.error(f"Unsupported file: {name}. Use .pkl or .json")
        return None


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### GreenTensor")
    st.markdown("Carbon-aware MLOps middleware")
    st.markdown("---")
    st.markdown("**Navigation**")
    page = st.radio("", ["Overview", "Energy Analysis", "Security Report", "How It Works"], label_visibility="collapsed")
    st.markdown("---")
    st.markdown("**Data Source**")
    mode = st.radio("", ["Manual Input", "Upload File"], label_visibility="collapsed")
    st.markdown("---")
    st.markdown("v0.3.0 — MIT License")
    st.markdown("Dhivya Balakumar")


# ── Data input ────────────────────────────────────────────────────────────────
baseline_metrics = None
optimized_metrics = None
security_alerts = []

if mode == "Manual Input":
    with st.expander("Enter run metrics manually", expanded=True):
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Baseline run** (without GreenTensor)")
            b_duration  = st.number_input("Duration (seconds)",    key="b_d",  min_value=0.0, value=0.0)
            b_energy    = st.number_input("Energy (kWh)",          key="b_e",  min_value=0.0, value=0.0, format="%.6f")
            b_emissions = st.number_input("Emissions (kg CO2)",    key="b_em", min_value=0.0, value=0.0, format="%.6f")
        with col2:
            st.markdown("**Optimized run** (with GreenTensor)")
            o_duration  = st.number_input("Duration (seconds)",    key="o_d",  min_value=0.0, value=0.0)
            o_energy    = st.number_input("Energy (kWh)",          key="o_e",  min_value=0.0, value=0.0, format="%.6f")
            o_emissions = st.number_input("Emissions (kg CO2)",    key="o_em", min_value=0.0, value=0.0, format="%.6f")

        if b_energy > 0 and o_energy > 0:
            baseline_metrics  = RunMetrics(duration_s=b_duration,  energy_kwh=b_energy,  emissions_kg=b_emissions)
            optimized_metrics = RunMetrics(duration_s=o_duration,  energy_kwh=o_energy,  emissions_kg=o_emissions)

else:
    with st.expander("Upload metrics files", expanded=True):
        st.markdown('<div class="section-title">How to get your files</div>', unsafe_allow_html=True)

        st.markdown("""
GreenTensor automatically saves measurement files after every training run.
You do not create these files manually — they are generated for you.
Follow these three steps:
        """)

        st.markdown("---")
        st.markdown("**Step 1 — Run your training without GreenTensor (baseline)**")
        st.markdown("""
Open a terminal in your project folder and run:
```bash
python examples/train_baseline.py
```
This runs your training loop with no optimizations and saves a file called
`baseline_metrics.pkl` in the same folder. That file records how much energy,
time, and CO2 your training consumed without any optimization.
        """)

        st.markdown("**Step 2 — Run your training with GreenTensor (optimized)**")
        st.markdown("""
```bash
python examples/train_optimized.py
```
This runs the same training loop wrapped in GreenTensor — GPU optimizations on,
carbon tracking active. It saves `optimized_metrics.pkl` in the same folder.
        """)

        st.markdown("**Step 3 — Upload both files below**")
        st.markdown("""
Upload `baseline_metrics.pkl` on the left and `optimized_metrics.pkl` on the right.
The dashboard will read both files, extract the measurements, calculate the savings,
and show you the comparison charts.

If you do not have `.pkl` files yet, you can also upload a `.json` file you create
manually. It must contain these four fields:
```json
{
    "duration_s": 45.2,
    "energy_kwh": 0.000412,
    "emissions_kg": 0.000096,
    "idle_seconds": 2.1
}
```
- `duration_s` — how long the training run took in seconds
- `energy_kwh` — energy consumed in kilowatt-hours
- `emissions_kg` — CO2 emissions in kilograms
- `idle_seconds` — time the GPU spent idle (put 0 if unknown)
        """)
        st.markdown("---")

        col1, col2 = st.columns(2)
        with col1:
            b_file = st.file_uploader("Baseline metrics file", type=["pkl", "json"], key="b_f")
            if b_file:
                baseline_metrics = load_metrics_file(b_file)
                if baseline_metrics:
                    st.success("Baseline file loaded successfully.")
                    st.dataframe(pd.DataFrame([{
                        "duration_s": baseline_metrics.duration_s,
                        "energy_kwh": baseline_metrics.energy_kwh,
                        "emissions_kg": baseline_metrics.emissions_kg,
                        "idle_seconds": baseline_metrics.idle_seconds,
                    }]), use_container_width=True)

        with col2:
            o_file = st.file_uploader("Optimized metrics file", type=["pkl", "json"], key="o_f")
            if o_file:
                optimized_metrics = load_metrics_file(o_file)
                if optimized_metrics:
                    st.success("Optimized file loaded successfully.")
                    st.dataframe(pd.DataFrame([{
                        "duration_s": optimized_metrics.duration_s,
                        "energy_kwh": optimized_metrics.energy_kwh,
                        "emissions_kg": optimized_metrics.emissions_kg,
                        "idle_seconds": optimized_metrics.idle_seconds,
                    }]), use_container_width=True)

        # Auto-load from disk
        if not baseline_metrics and os.path.exists("baseline_metrics.pkl"):
            with open("baseline_metrics.pkl", "rb") as f:
                baseline_metrics = pickle.load(f)
            st.info("Auto-loaded baseline_metrics.pkl from current directory.")


# ── Pages ─────────────────────────────────────────────────────────────────────

if page == "Overview":
    st.markdown('<div class="section-title">Overview</div>', unsafe_allow_html=True)

    if not baseline_metrics:
        st.info("No data loaded. Use the sidebar to enter metrics manually or upload files.")
    elif baseline_metrics and not optimized_metrics:
        st.markdown("**Baseline run loaded — awaiting optimized run for comparison.**")
        col1, col2, col3 = st.columns(3)
        with col1: metric_card("Duration", f"{baseline_metrics.duration_s:.2f} s")
        with col2: metric_card("Energy Used", f"{baseline_metrics.energy_kwh:.6f} kWh")
        with col3: metric_card("CO2 Emissions", f"{baseline_metrics.emissions_kg:.6f} kg")
    else:
        savings = calculate_savings(baseline_metrics, optimized_metrics)
        st.markdown("**Baseline vs Optimized — Summary**")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            metric_card("Energy Reduction", f"{savings['energy_reduction_pct']:.1f}%",
                        delta="vs baseline", delta_good=True)
        with col2:
            metric_card("Energy Saved", f"{savings['energy_saved_kwh']:.6f} kWh",
                        delta=f"from {baseline_metrics.energy_kwh:.6f} kWh", delta_good=True)
        with col3:
            metric_card("CO2 Saved", f"{savings['emissions_saved_kg']:.6f} kg",
                        delta=f"from {baseline_metrics.emissions_kg:.6f} kg", delta_good=True)
        with col4:
            metric_card("Time Saved", f"{savings['time_saved_s']:.2f} s",
                        delta=f"from {baseline_metrics.duration_s:.2f} s", delta_good=True)


elif page == "Energy Analysis":
    st.markdown('<div class="section-title">Energy Analysis</div>', unsafe_allow_html=True)

    if not baseline_metrics:
        st.info("No data loaded.")
    else:
        if optimized_metrics:
            savings = calculate_savings(baseline_metrics, optimized_metrics)

            st.markdown("**Energy consumption (kWh)**")
            st.bar_chart(pd.DataFrame({
                "Energy (kWh)": [baseline_metrics.energy_kwh, optimized_metrics.energy_kwh]
            }, index=["Baseline", "Optimized"]))

            st.markdown("**CO2 emissions (kg)**")
            st.bar_chart(pd.DataFrame({
                "Emissions (kg CO2)": [baseline_metrics.emissions_kg, optimized_metrics.emissions_kg]
            }, index=["Baseline", "Optimized"]))

            st.markdown("**Runtime (seconds)**")
            st.bar_chart(pd.DataFrame({
                "Duration (s)": [baseline_metrics.duration_s, optimized_metrics.duration_s]
            }, index=["Baseline", "Optimized"]))

            st.markdown("---")
            st.markdown("**Detailed breakdown**")
            st.dataframe(pd.DataFrame([
                {
                    "Run": "Baseline",
                    "Duration (s)": baseline_metrics.duration_s,
                    "Energy (kWh)": baseline_metrics.energy_kwh,
                    "Emissions (kg)": baseline_metrics.emissions_kg,
                    "Idle (s)": baseline_metrics.idle_seconds,
                },
                {
                    "Run": "Optimized",
                    "Duration (s)": optimized_metrics.duration_s,
                    "Energy (kWh)": optimized_metrics.energy_kwh,
                    "Emissions (kg)": optimized_metrics.emissions_kg,
                    "Idle (s)": optimized_metrics.idle_seconds,
                },
                {
                    "Run": "Saved",
                    "Duration (s)": savings["time_saved_s"],
                    "Energy (kWh)": savings["energy_saved_kwh"],
                    "Emissions (kg)": savings["emissions_saved_kg"],
                    "Idle (s)": "-",
                },
            ]).set_index("Run"), use_container_width=True)
        else:
            st.markdown("**Baseline energy data**")
            st.bar_chart(pd.DataFrame({
                "Energy (kWh)": [baseline_metrics.energy_kwh]
            }, index=["Baseline"]))
            st.info("Upload optimized metrics to see comparison charts.")


elif page == "Security Report":
    st.markdown('<div class="section-title">Security Report</div>', unsafe_allow_html=True)
    st.markdown("""
GreenTensor monitors the GPU power draw continuously during training.
Anomalous patterns in the carbon footprint signal potential threats in the MLOps pipeline.

**Detection methods:**
- **alibi-detect SpectralResidual** — statistical frequency-domain analysis of the power time series. Flags points that deviate from the expected pattern, not just a fixed threshold.
- **Threshold detector** — fallback when alibi-detect is unavailable. Alerts when power exceeds baseline by a configurable percentage.
- **LLM Guard** — scans model inputs for prompt injection and secrets, and model outputs for sensitive data leakage.

**Threat types detected:**

| Threat | What it means |
|--------|---------------|
| `power_spike` | Sudden energy surge — possible cryptominer injected into the pipeline |
| `idle_drain` | GPU consuming power while idle — possible hidden background process or data exfiltration |
| `prompt_injection` | Adversarial input targeting the model — detected by LLM Guard |
| `data_leakage` | Sensitive data in model output — detected by LLM Guard |
    """)

    if not security_alerts:
        st.markdown('<div class="clean-badge">CLEAN — No threats detected in this session</div>', unsafe_allow_html=True)
        st.markdown("")
        st.markdown("Security alerts appear here automatically when GreenTensor detects anomalous energy patterns during a live training run.")
    else:
        st.markdown(f'<div class="threat-badge">THREATS DETECTED — {len(security_alerts)} alert(s)</div>', unsafe_allow_html=True)
        st.markdown("")
        for a in security_alerts:
            css = f"alert-{a.severity}"
            st.markdown(f"""
            <div class="{css}">
                <span class="tag tag-type">{a.alert_type.upper()}</span>
                <span class="tag tag-source">{a.source}</span>
                <strong>{a.severity.upper()}</strong><br>
                {a.message}
            </div>""", unsafe_allow_html=True)


elif page == "How It Works":
    st.markdown('<div class="section-title">How GreenTensor Works</div>', unsafe_allow_html=True)
    st.markdown("""
**What is GreenTensor?**

GreenTensor is a Python middleware package for PyTorch ML workloads.
It wraps your existing training code with one context manager and adds four capabilities
without requiring any changes to your model or training logic.

---

**Usage**

```python
from greentensor import GreenTensor

with GreenTensor() as gt:
    with gt.mixed_precision():
        train()   # your existing code, unchanged
```

---

**What happens inside the context manager**

When you enter `with GreenTensor()`:

1. GPU optimizer applies cuDNN benchmark mode and enables mixed precision (FP16).
   This reduces memory usage and speeds up matrix operations on CUDA GPUs.

2. Idle optimizer starts a background thread sampling GPU utilization every 0.5 seconds.
   If utilization drops below 10%, it records idle time to quantify wasted energy.

3. Anomaly detector starts a second background thread sampling GPU power draw every second.
   It builds a rolling baseline of normal power consumption and flags deviations.

4. CodeCarbon starts tracking carbon emissions using your region's grid carbon intensity.
   If CodeCarbon is unavailable, GreenTensor falls back to nvidia-smi power sampling.

When you exit the context:

5. All threads stop and measurements are collected.
6. A RunMetrics object is created with duration, energy, emissions, and idle time.
7. If a baseline RunMetrics was passed in, savings are calculated against real measured data.
8. A report is printed to the terminal.

---

**The file upload in this dashboard**

When you run `train_baseline.py` or `train_optimized.py`, GreenTensor saves a
`RunMetrics` object to a `.pkl` file using Python's pickle serialization.

That file contains exactly four values:
- `duration_s` — wall-clock time of the run
- `energy_kwh` — energy measured by CodeCarbon or nvidia-smi
- `emissions_kg` — CO2 calculated from energy and grid carbon intensity
- `idle_seconds` — time the GPU spent below the utilization threshold

When you upload that file here, the dashboard deserializes it back into a `RunMetrics`
object, computes the savings between baseline and optimized, and renders the charts.

You can also create a `.json` file manually with the same four fields if you want to
enter data from an external source or a different tool.

---

**Security monitoring**

The anomaly detector uses the SpectralResidual algorithm from alibi-detect (Apache 2.0).
This is the same algorithm Microsoft uses in Azure Metrics Advisor for production anomaly detection.

It works by computing the Fourier transform of the power time series, removing the
expected frequency components, and flagging residuals that exceed a threshold.
This catches subtle, sustained anomalies that a simple threshold would miss.

LLM Guard (MIT, by Protect AI) adds a second layer by scanning model inputs and outputs
for prompt injection patterns, leaked secrets, and sensitive data.

Install the full security stack with:
```bash
pip install greentensor[security]
```
    """)
