import streamlit as st
import pickle
import json
import os
import pandas as pd
from greentensor.report.metrics import (
    RunMetrics, calculate_savings, DatacenterConfig, PUE_PRESETS
)
from greentensor.report.esg import ESGReporter, ESGOrganization
from greentensor.core.history import RunHistory
from greentensor.water.aquatensor import AquaTensorBridge, AquaTensorConfig, PROVIDER_WUE, REGIONAL_WATER_STRESS

st.set_page_config(
    page_title="GreenTensor Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Global styles ─────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    .metric-card {
        background: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 6px;
        padding: 1.2rem 1.5rem;
        margin-bottom: 0.5rem;
    }
    .metric-label { font-size: 0.78rem; color: #6c757d; text-transform: uppercase; letter-spacing: 0.05em; }
    .metric-value { font-size: 1.6rem; font-weight: 700; color: #212529; }
    .metric-delta-good { font-size: 0.85rem; color: #198754; font-weight: 600; }
    .metric-delta-bad  { font-size: 0.85rem; color: #dc3545; font-weight: 600; }
    .section-title { font-size: 1.1rem; font-weight: 700; color: #212529;
                     border-bottom: 2px solid #dee2e6; padding-bottom: 0.4rem; margin-bottom: 1rem; }
    .alert-critical { background:#fff5f5; border-left:4px solid #dc3545; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-high     { background:#fff8f0; border-left:4px solid #fd7e14; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-medium   { background:#fffdf0; border-left:4px solid #ffc107; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .alert-low      { background:#f0fff4; border-left:4px solid #198754; padding:0.8rem 1rem; margin:0.4rem 0; border-radius:4px; }
    .tag { display:inline-block; padding:0.15rem 0.5rem; border-radius:3px;
           font-size:0.72rem; font-weight:700; letter-spacing:0.04em; margin-right:0.3rem; }
    .tag-source { background:#e9ecef; color:#495057; }
    .tag-type   { background:#cfe2ff; color:#084298; }
    .clean-badge { background:#d1e7dd; color:#0a3622; padding:0.4rem 1rem;
                   border-radius:4px; font-weight:600; display:inline-block; }
    .threat-badge { background:#f8d7da; color:#58151c; padding:0.4rem 1rem;
                    border-radius:4px; font-weight:600; display:inline-block; }
    hr { border: none; border-top: 1px solid #dee2e6; margin: 1.5rem 0; }
</style>
""", unsafe_allow_html=True)


# ── Helpers ───────────────────────────────────────────────────────────────────
def metric_card(label, value, delta=None, delta_good=True):
    delta_html = ""
    if delta:
        cls = "metric-delta-good" if delta_good else "metric-delta-bad"
        delta_html = f'<div class="{cls}">{delta}</div>'
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-label">{label}</div>
        <div class="metric-value">{value}</div>
        {delta_html}
    </div>""", unsafe_allow_html=True)


def load_metrics_file(file) -> RunMetrics:
    """
    Accepts .pkl (binary, auto-generated by GreenTensor) or
    .json (human-readable, manually created).
    Returns a RunMetrics dataclass.
    """
    name = file.name.lower()
    if name.endswith(".pkl"):
        return pickle.load(file)
    elif name.endswith(".json"):
        data = json.load(file)
        return RunMetrics(
            duration_s=float(data["duration_s"]),
            energy_kwh=float(data["energy_kwh"]),
            emissions_kg=float(data["emissions_kg"]),
            idle_seconds=float(data.get("idle_seconds", 0.0)),
        )
    else:
        st.error(f"Unsupported file: {name}. Use .pkl or .json")
        return None


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### GreenTensor")
    st.markdown("Carbon-aware MLOps middleware")
    st.markdown("---")
    st.markdown("**Navigation**")
    page = st.radio("", ["Overview", "Energy Analysis", "Water Intelligence", "Datacenter Impact", "ESG Report", "Run History", "Security Report", "How It Works"], label_visibility="collapsed")
    st.markdown("---")
    st.markdown("**Data Source**")
    mode = st.radio("", ["Manual Input", "Upload File"], label_visibility="collapsed")
    st.markdown("---")
    st.markdown("v0.3.0 — MIT License")
    st.markdown("Dhivya Balakumar")


# ── Data input ────────────────────────────────────────────────────────────────
baseline_metrics = None
optimized_metrics = None
security_alerts = []

if mode == "Manual Input":
    with st.expander("Enter run metrics manually", expanded=True):
        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Baseline run** (without GreenTensor)")
            b_duration  = st.number_input("Duration (seconds)",    key="b_d",  min_value=0.0, value=0.0)
            b_energy    = st.number_input("Energy (kWh)",          key="b_e",  min_value=0.0, value=0.0, format="%.6f")
            b_emissions = st.number_input("Emissions (kg CO2)",    key="b_em", min_value=0.0, value=0.0, format="%.6f")
        with col2:
            st.markdown("**Optimized run** (with GreenTensor)")
            o_duration  = st.number_input("Duration (seconds)",    key="o_d",  min_value=0.0, value=0.0)
            o_energy    = st.number_input("Energy (kWh)",          key="o_e",  min_value=0.0, value=0.0, format="%.6f")
            o_emissions = st.number_input("Emissions (kg CO2)",    key="o_em", min_value=0.0, value=0.0, format="%.6f")

        if b_energy > 0 and o_energy > 0:
            baseline_metrics  = RunMetrics(duration_s=b_duration,  energy_kwh=b_energy,  emissions_kg=b_emissions)
            optimized_metrics = RunMetrics(duration_s=o_duration,  energy_kwh=o_energy,  emissions_kg=o_emissions)

else:
    with st.expander("Upload metrics files", expanded=True):
        st.markdown('<div class="section-title">How to get your files</div>', unsafe_allow_html=True)

        st.markdown("""
GreenTensor automatically saves measurement files after every training run.
You do not create these files manually — they are generated for you.
Follow these three steps:
        """)

        st.markdown("---")
        st.markdown("**Step 1 — Run your training without GreenTensor (baseline)**")
        st.markdown("""
Open a terminal in your project folder and run:
```bash
python examples/train_baseline.py
```
This runs your training loop with no optimizations and saves a file called
`baseline_metrics.pkl` in the same folder. That file records how much energy,
time, and CO2 your training consumed without any optimization.
        """)

        st.markdown("**Step 2 — Run your training with GreenTensor (optimized)**")
        st.markdown("""
```bash
python examples/train_optimized.py
```
This runs the same training loop wrapped in GreenTensor — GPU optimizations on,
carbon tracking active. It saves `optimized_metrics.pkl` in the same folder.
        """)

        st.markdown("**Step 3 — Upload both files below**")
        st.markdown("""
Upload `baseline_metrics.pkl` on the left and `optimized_metrics.pkl` on the right.
The dashboard will read both files, extract the measurements, calculate the savings,
and show you the comparison charts.

If you do not have `.pkl` files yet, you can also upload a `.json` file you create
manually. It must contain these four fields:
```json
{
    "duration_s": 45.2,
    "energy_kwh": 0.000412,
    "emissions_kg": 0.000096,
    "idle_seconds": 2.1
}
```
- `duration_s` — how long the training run took in seconds
- `energy_kwh` — energy consumed in kilowatt-hours
- `emissions_kg` — CO2 emissions in kilograms
- `idle_seconds` — time the GPU spent idle (put 0 if unknown)
        """)
        st.markdown("---")

        col1, col2 = st.columns(2)
        with col1:
            b_file = st.file_uploader("Baseline metrics file", type=["pkl", "json"], key="b_f")
            if b_file:
                baseline_metrics = load_metrics_file(b_file)
                if baseline_metrics:
                    st.success("Baseline file loaded successfully.")
                    st.dataframe(pd.DataFrame([{
                        "duration_s": baseline_metrics.duration_s,
                        "energy_kwh": baseline_metrics.energy_kwh,
                        "emissions_kg": baseline_metrics.emissions_kg,
                        "idle_seconds": baseline_metrics.idle_seconds,
                    }]), use_container_width=True)

        with col2:
            o_file = st.file_uploader("Optimized metrics file", type=["pkl", "json"], key="o_f")
            if o_file:
                optimized_metrics = load_metrics_file(o_file)
                if optimized_metrics:
                    st.success("Optimized file loaded successfully.")
                    st.dataframe(pd.DataFrame([{
                        "duration_s": optimized_metrics.duration_s,
                        "energy_kwh": optimized_metrics.energy_kwh,
                        "emissions_kg": optimized_metrics.emissions_kg,
                        "idle_seconds": optimized_metrics.idle_seconds,
                    }]), use_container_width=True)

        # Auto-load from disk
        if not baseline_metrics and os.path.exists("baseline_metrics.pkl"):
            with open("baseline_metrics.pkl", "rb") as f:
                baseline_metrics = pickle.load(f)
            st.info("Auto-loaded baseline_metrics.pkl from current directory.")


# ── Pages ─────────────────────────────────────────────────────────────────────

if page == "Overview":
    st.markdown('<div class="section-title">Overview</div>', unsafe_allow_html=True)

    if not baseline_metrics:
        st.info("No data loaded. Use the sidebar to enter metrics manually or upload files.")
    elif baseline_metrics and not optimized_metrics:
        st.markdown("**Baseline run loaded — awaiting optimized run for comparison.**")
        col1, col2, col3 = st.columns(3)
        with col1: metric_card("Duration", f"{baseline_metrics.duration_s:.2f} s")
        with col2: metric_card("Energy Used", f"{baseline_metrics.energy_kwh:.6f} kWh")
        with col3: metric_card("CO2 Emissions", f"{baseline_metrics.emissions_kg:.6f} kg")
    else:
        savings = calculate_savings(baseline_metrics, optimized_metrics)
        st.markdown("**Baseline vs Optimized — Summary**")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            metric_card("Energy Reduction", f"{savings['energy_reduction_pct']:.1f}%",
                        delta="vs baseline", delta_good=True)
        with col2:
            metric_card("Energy Saved", f"{savings['energy_saved_kwh']:.6f} kWh",
                        delta=f"from {baseline_metrics.energy_kwh:.6f} kWh", delta_good=True)
        with col3:
            metric_card("CO2 Saved", f"{savings['emissions_saved_kg']:.6f} kg",
                        delta=f"from {baseline_metrics.emissions_kg:.6f} kg", delta_good=True)
        with col4:
            metric_card("Time Saved", f"{savings['time_saved_s']:.2f} s",
                        delta=f"from {baseline_metrics.duration_s:.2f} s", delta_good=True)


elif page == "Energy Analysis":
    st.markdown('<div class="section-title">Energy Analysis</div>', unsafe_allow_html=True)

    if not baseline_metrics:
        st.info("No data loaded.")
    else:
        if optimized_metrics:
            savings = calculate_savings(baseline_metrics, optimized_metrics)

            st.markdown("**Energy consumption (kWh)**")
            st.bar_chart(pd.DataFrame({
                "Energy (kWh)": [baseline_metrics.energy_kwh, optimized_metrics.energy_kwh]
            }, index=["Baseline", "Optimized"]))

            st.markdown("**CO2 emissions (kg)**")
            st.bar_chart(pd.DataFrame({
                "Emissions (kg CO2)": [baseline_metrics.emissions_kg, optimized_metrics.emissions_kg]
            }, index=["Baseline", "Optimized"]))

            st.markdown("**Runtime (seconds)**")
            st.bar_chart(pd.DataFrame({
                "Duration (s)": [baseline_metrics.duration_s, optimized_metrics.duration_s]
            }, index=["Baseline", "Optimized"]))

            st.markdown("---")
            st.markdown("**Detailed breakdown**")
            st.dataframe(pd.DataFrame([
                {
                    "Run": "Baseline",
                    "Duration (s)": baseline_metrics.duration_s,
                    "Energy (kWh)": baseline_metrics.energy_kwh,
                    "Emissions (kg)": baseline_metrics.emissions_kg,
                    "Idle (s)": baseline_metrics.idle_seconds,
                },
                {
                    "Run": "Optimized",
                    "Duration (s)": optimized_metrics.duration_s,
                    "Energy (kWh)": optimized_metrics.energy_kwh,
                    "Emissions (kg)": optimized_metrics.emissions_kg,
                    "Idle (s)": optimized_metrics.idle_seconds,
                },
                {
                    "Run": "Saved",
                    "Duration (s)": savings["time_saved_s"],
                    "Energy (kWh)": savings["energy_saved_kwh"],
                    "Emissions (kg)": savings["emissions_saved_kg"],
                    "Idle (s)": "-",
                },
            ]).set_index("Run"), use_container_width=True)
        else:
            st.markdown("**Baseline energy data**")
            st.bar_chart(pd.DataFrame({
                "Energy (kWh)": [baseline_metrics.energy_kwh]
            }, index=["Baseline"]))
            st.info("Upload optimized metrics to see comparison charts.")


elif page == "Water Intelligence":
    st.markdown('<div class="section-title">AquaTensor Water Intelligence</div>', unsafe_allow_html=True)
    st.markdown("""
Every watt of GPU compute generates waste heat. AquaTensor captures that heat
and converts it to fresh water via membrane distillation. GreenTensor measures
the real compute, calculates the heat generated, and predicts exactly how much
water AquaTensor can produce — per training job, per model, per day.
    """)

    st.markdown("---")
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Datacenter / Cloud Provider**")
        provider = st.selectbox("Provider", list(PROVIDER_WUE.keys()),
                                format_func=lambda k: f"{k}  (WUE: {PROVIDER_WUE[k] or 'custom'})")
        custom_wue = None
        if provider == "custom":
            custom_wue = st.number_input("Custom WUE (L/kWh)", min_value=0.1, value=1.8, step=0.1)

        region = st.selectbox("Region (water stress)", list(REGIONAL_WATER_STRESS.keys()))

        st.markdown("**AquaTensor Hardware**")
        aquatensor_installed = st.toggle("AquaTensor MD system installed", value=True)
        if aquatensor_installed:
            whr = st.slider("Waste Heat Recovery ratio", 0.1, 1.0, 0.65, 0.05,
                            help="Fraction of GPU heat captured by AquaTensor")
            feed_temp = st.slider("Coolant feed temperature (C)", 40, 80, 60,
                                  help="Temperature of liquid coolant fed to membrane")
        else:
            whr = 0.0
            feed_temp = 60

    with col2:
        st.markdown("**Membrane Distillation Reference**")
        st.markdown("""
| Feed Temp | MD Yield |
|-----------|----------|
| 40 C | 2.5 L/kWh |
| 50 C | 4.0 L/kWh |
| 60 C | 5.5 L/kWh |
| 70 C | 7.0 L/kWh |
| 80 C | 8.5 L/kWh |

Source: Khayet & Matsuura, Membrane Distillation (2011)

**Regional Water Stress (WRI Aqueduct)**
        """)
        stress_df = pd.DataFrame([
            {"Region": k, "Stress Index": v,
             "Level": "Extremely High" if v >= 4 else "High" if v >= 3 else "Medium" if v >= 2 else "Low"}
            for k, v in REGIONAL_WATER_STRESS.items()
        ])
        st.dataframe(stress_df, use_container_width=True, hide_index=True)

    st.markdown("---")

    # Build config and calculate
    aq_config = AquaTensorConfig(
        provider=provider,
        custom_wue=custom_wue,
        region=region,
        aquatensor_installed=aquatensor_installed,
        whr_ratio=whr,
        feed_temperature_c=float(feed_temp),
    )
    bridge = AquaTensorBridge(aq_config)

    if baseline_metrics:
        water = bridge.calculate_water_metrics(baseline_metrics.energy_kwh, baseline_metrics.duration_s)

        st.markdown("**Water metrics for loaded run**")
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            metric_card("Energy Used", f"{baseline_metrics.energy_kwh:.6f} kWh")
        with c2:
            metric_card("Water Consumed", f"{water.water_consumed_liters:.3f} L",
                        delta=f"WUE {water.wue} L/kWh", delta_good=False)
        with c3:
            if aquatensor_installed:
                metric_card("Water Produced", f"{water.water_produced_liters:.3f} L",
                            delta=f"via AquaTensor MD @ {feed_temp}C", delta_good=True)
            else:
                metric_card("Water Produced", "0.000 L", delta="AquaTensor not installed")
        with c4:
            net = water.net_water_impact_liters
            good = net < 0
            label = "NET POSITIVE" if good else "net negative"
            metric_card("Net Water Impact", f"{net:.3f} L", delta=label, delta_good=good)

        if aquatensor_installed and water.water_produced_liters > 0:
            st.markdown("---")
            st.markdown("**What this means**")
            st.markdown(f"""
- This compute session generated **{water.heat_generated_kwh:.6f} kWh** of waste heat
- AquaTensor captured **{water.heat_recovered_kwh:.6f} kWh** ({whr*100:.0f}% recovery)
- At {feed_temp}C feed temperature, membrane distillation yield is **{water.md_yield_liters_per_kwh:.1f} L/kWh**
- **{water.water_produced_liters:.3f} liters** of fresh water produced
- Equivalent to **{water.drinking_water_days:.1f} person-days** of drinking water
- Region water stress: **{water.water_stress_label}** (index {water.water_stress_index}/5.0)
            """)

        # Forecast section
        st.markdown("---")
        st.markdown("**Heat Forecast for Upcoming Jobs**")
        st.markdown("Enter your queued training jobs to predict water yield:")

        n_jobs = st.number_input("Number of queued jobs", 1, 10, 3)
        jobs = []
        for i in range(int(n_jobs)):
            c1, c2, c3 = st.columns(3)
            with c1:
                name = st.text_input(f"Job {i+1} name", value=f"training_job_{i+1}", key=f"jn{i}")
            with c2:
                dur = st.number_input(f"Duration (hours)", 0.5, 72.0, 2.0, key=f"jd{i}")
            with c3:
                pwr = st.number_input(f"Est. GPU power (W)", 50, 1000, 300, key=f"jp{i}")
            jobs.append({"name": name, "estimated_duration_s": dur * 3600,
                         "estimated_power_w": pwr})

        if st.button("Forecast water yield"):
            forecast = bridge.forecast_heat(jobs)
            st.markdown(f"""
**Forecast results:**
- Total compute energy: **{forecast.predicted_energy_kwh:.3f} kWh**
- Heat recovered by AquaTensor: **{forecast.predicted_heat_kwh:.3f} kWh**
- Predicted water production: **{forecast.predicted_water_liters:.1f} liters**
- MD viable at current temperature: **{"Yes" if forecast.temperature_sustained else "No"}**

**Recommendation:** {forecast.optimal_schedule_recommendation}
            """)
    else:
        st.info("Load metrics from the sidebar to see water calculations.")

    st.markdown("---")
    st.markdown("**The AquaTensor + GreenTensor Loop**")
    st.markdown("""
```
AI Training Job
      |
      v
GreenTensor measures real GPU power (W)
      |
      v
Heat generated = Power consumed (conservation of energy)
      |
      v
AquaTensor captures waste heat via liquid cooling loop
      |
      v
Membrane distillation converts heat to fresh water
      |
      v
GreenTensor reports: energy used, CO2 emitted, water produced
      |
      v
Net environmental impact: less carbon, more water
```
    """)


elif page == "Datacenter Impact":
    st.markdown('<div class="section-title">Datacenter Impact</div>', unsafe_allow_html=True)
    st.markdown("""
When your training runs inside a datacenter — cloud VM, HPC cluster, or on-premise DC —
the actual energy consumed is higher than what your GPU reports. Cooling systems, UPS,
lighting, and networking all add overhead. GreenTensor accounts for this using two factors:

**PUE (Power Usage Effectiveness)** — the ratio of total DC power to IT equipment power.
A PUE of 1.5 means for every 1W your GPU uses, the datacenter uses 1.5W in total.

**Carbon intensity** — how much CO2 your region's electricity grid produces per kWh.
A datacenter in Norway (hydro-heavy grid) has far lower emissions than one in Poland (coal-heavy).
    """)

    st.markdown("---")
    st.markdown("**Configure your datacenter**")

    col1, col2 = st.columns(2)
    with col1:
        preset_label = st.selectbox(
            "DC type (sets PUE automatically)",
            options=[
                "local_workstation  — PUE 1.0 (no DC overhead)",
                "hyperscale         — PUE 1.1 (Google / Microsoft / Meta)",
                "cloud_average      — PUE 1.2 (AWS / GCP / Azure average)",
                "enterprise_dc      — PUE 1.5 (typical on-premise DC)",
                "legacy_dc          — PUE 1.8 (older / inefficient DC)",
                "custom             — enter your own PUE",
            ]
        )
        preset_key = preset_label.split()[0]
        preset_pue = PUE_PRESETS.get(preset_key, 1.2)

        if preset_key == "custom":
            pue = st.number_input("Custom PUE", min_value=1.0, max_value=3.0, value=1.2, step=0.05)
        else:
            pue = preset_pue
            st.info(f"PUE set to {pue}")

        num_nodes = st.number_input(
            "Number of training nodes",
            min_value=1, max_value=1024, value=1, step=1,
            help="For distributed training across multiple GPUs/machines. Single machine = 1."
        )

    with col2:
        st.markdown("**Regional carbon intensity (kg CO2 per kWh)**")
        st.markdown("""
Find your value at [electricitymap.org](https://app.electricitymap.org)

Common values:
| Region | kg CO2 / kWh |
|--------|-------------|
| Norway (hydro) | 0.017 |
| France (nuclear) | 0.056 |
| UK average | 0.233 |
| World average | 0.233 |
| USA average | 0.386 |
| Australia | 0.490 |
| Poland (coal) | 0.635 |
        """)
        carbon_intensity = st.number_input(
            "Carbon intensity (kg CO2 / kWh)",
            min_value=0.0, max_value=2.0,
            value=0.000233, format="%.6f",
            help="World average is 0.000233. Use electricitymap.org for your DC region."
        )
        dc_name = st.text_input("Datacenter name (optional)", value="My DC")

    dc_config = DatacenterConfig(
        pue=pue,
        carbon_intensity_kg_per_kwh=carbon_intensity,
        num_nodes=int(num_nodes),
        dc_name=dc_name or "custom",
    )

    st.markdown("---")

    if not baseline_metrics:
        st.info("No run data loaded. Go to the sidebar and load metrics first.")
    else:
        b_dc = baseline_metrics.apply_datacenter_config(dc_config)
        o_dc = optimized_metrics.apply_datacenter_config(dc_config) if optimized_metrics else None

        st.markdown("**Datacenter-adjusted energy for baseline run**")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            metric_card("Raw GPU Energy", f"{baseline_metrics.energy_kwh:.6f} kWh")
        with col2:
            metric_card("PUE Multiplier", f"x {pue}")
        with col3:
            metric_card("Nodes", f"x {int(num_nodes)}")
        with col4:
            metric_card("Total DC Energy", f"{b_dc.energy_kwh_dc:.6f} kWh",
                        delta=f"+{((b_dc.energy_kwh_dc / baseline_metrics.energy_kwh) - 1) * 100:.0f}% overhead",
                        delta_good=False)

        st.markdown(f"**Total DC CO2 emissions: {b_dc.emissions_kg_dc:.6f} kg**")
        st.caption(f"Calculated as: {baseline_metrics.energy_kwh:.6f} kWh x PUE {pue} x {int(num_nodes)} nodes x {carbon_intensity:.6f} kg/kWh")

        if o_dc:
            st.markdown("---")
            st.markdown("**Savings with datacenter overhead applied**")
            savings_dc = calculate_savings(b_dc, o_dc, use_dc_adjusted=True)
            col1, col2, col3 = st.columns(3)
            with col1:
                metric_card("DC Energy Reduction", f"{savings_dc['energy_reduction_pct']:.1f}%",
                            delta="vs baseline", delta_good=True)
            with col2:
                metric_card("DC Energy Saved", f"{savings_dc['energy_saved_kwh']:.6f} kWh",
                            delta_good=True)
            with col3:
                metric_card("DC CO2 Saved", f"{savings_dc['emissions_saved_kg']:.6f} kg",
                            delta_good=True)

            st.markdown("**DC-adjusted energy comparison**")
            st.bar_chart(pd.DataFrame({
                "DC Energy (kWh)": [b_dc.energy_kwh_dc, o_dc.energy_kwh_dc]
            }, index=["Baseline (DC)", "Optimized (DC)"]))

            st.markdown("**Raw vs DC-adjusted comparison**")
            st.dataframe(pd.DataFrame([
                {"Metric": "Baseline raw energy (kWh)",      "Value": baseline_metrics.energy_kwh},
                {"Metric": "Baseline DC energy (kWh)",       "Value": b_dc.energy_kwh_dc},
                {"Metric": "Optimized raw energy (kWh)",     "Value": optimized_metrics.energy_kwh},
                {"Metric": "Optimized DC energy (kWh)",      "Value": o_dc.energy_kwh_dc},
                {"Metric": "DC energy saved (kWh)",          "Value": savings_dc["energy_saved_kwh"]},
                {"Metric": "DC CO2 saved (kg)",              "Value": savings_dc["emissions_saved_kg"]},
                {"Metric": "Reduction (%)",                  "Value": f"{savings_dc['energy_reduction_pct']:.1f}%"},
            ]).set_index("Metric"), use_container_width=True)


elif page == "ESG Report":
    st.markdown('<div class="section-title">ESG Report — Scope 2 Emissions</div>', unsafe_allow_html=True)
    st.markdown("""
This page generates a structured ESG report covering Scope 2 carbon emissions
from your AI/ML workloads, aligned with GHG Protocol, SEC climate disclosure rules,
and EU CSRD requirements.
    """)

    st.markdown("**Organization details**")
    col1, col2 = st.columns(2)
    with col1:
        org_name = st.text_input("Organization name", value="My Organization")
        reporting_period = st.text_input("Reporting period", value="FY2025")
        region = st.text_input("Region", value="US-East")
    with col2:
        carbon_intensity = st.number_input("Grid carbon intensity (kg CO2/kWh)",
                                           value=0.000233, format="%.6f")
        reporting_standard = st.selectbox("Reporting standard", [
            "GHG Protocol Scope 2",
            "SEC Climate Disclosure Rules",
            "EU CSRD",
            "ISO 14064-1",
        ])
        contact = st.text_input("Contact email (optional)", value="")

    st.markdown("---")
    st.markdown("**Add runs to this report**")

    history = RunHistory()
    records = history.all()

    if records:
        st.markdown(f"Found {len(records)} run(s) in local history.")
        df_hist = pd.DataFrame(records)
        st.dataframe(df_hist[["datetime", "model_name", "stage",
                               "energy_kwh", "emissions_kg", "duration_s"]],
                     use_container_width=True, hide_index=True)
    elif baseline_metrics:
        st.info("No run history file found. Using currently loaded metrics.")
    else:
        st.info("No run data available. Load metrics or run training scripts first.")

    if st.button("Generate ESG Report", type="primary"):
        org = ESGOrganization(
            name=org_name,
            reporting_period=reporting_period,
            region=region,
            carbon_intensity_kg_per_kwh=carbon_intensity,
            reporting_standard=reporting_standard,
            contact_email=contact,
        )
        reporter = ESGReporter(org)

        # Add from history
        for r in records:
            from greentensor.report.esg import ESGRunRecord
            reporter._runs.append(ESGRunRecord(
                run_id=r.get("datetime", ""),
                timestamp=r.get("timestamp", 0),
                model_name=r.get("model_name", "unknown"),
                stage=r.get("stage", "training"),
                duration_s=r.get("duration_s", 0),
                energy_kwh=r.get("energy_kwh", 0),
                emissions_kg=r.get("emissions_kg", 0),
            ))

        # Add currently loaded metrics if no history
        if not records and baseline_metrics:
            from greentensor.report.esg import ESGRunRecord
            import time as _time
            reporter._runs.append(ESGRunRecord(
                run_id="loaded_baseline",
                timestamp=_time.time(),
                model_name="loaded_model",
                stage="training",
                duration_s=baseline_metrics.duration_s,
                energy_kwh=baseline_metrics.energy_kwh,
                emissions_kg=baseline_metrics.emissions_kg,
            ))

        report = reporter.generate_report()

        st.markdown("---")
        st.markdown("**Generated Report**")
        st.code(report.to_text(), language=None)

        col1, col2 = st.columns(2)
        with col1:
            st.download_button(
                "Download JSON report",
                data=report.to_json(),
                file_name=f"greentensor_esg_{reporting_period.replace(' ', '_')}.json",
                mime="application/json",
            )
        with col2:
            st.download_button(
                "Download text report",
                data=report.to_text(),
                file_name=f"greentensor_esg_{reporting_period.replace(' ', '_')}.txt",
                mime="text/plain",
            )

        # Summary metrics
        st.markdown("**Summary**")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Total Runs", report.total_runs)
        c2.metric("Total Energy (DC)", f"{report.total_energy_kwh_dc:.4f} kWh")
        c3.metric("Total CO2 (DC)", f"{report.total_emissions_kg_dc:.4f} kg")
        c4.metric("Equiv. km driven", f"{report.emissions_equiv_km_driven:.1f}")


elif page == "Run History":
    st.markdown('<div class="section-title">Run History</div>', unsafe_allow_html=True)
    st.markdown("All training and inference runs recorded by GreenTensor on this machine.")

    history = RunHistory()
    records = history.all()

    if not records:
        st.info("No run history yet. Runs are recorded automatically when you use GreenTensor.")
        st.markdown("To record a run manually after loading metrics:")
        st.code("""
from greentensor.core.history import RunHistory
from greentensor import GreenTensor

history = RunHistory()

with GreenTensor() as gt:
    train()

history.record(gt.metrics, model_name="MyModel", stage="training")
        """)
    else:
        df = pd.DataFrame(records)
        st.markdown(f"**{len(records)} runs recorded**")

        st.dataframe(
            df[["datetime", "model_name", "stage", "duration_s",
                "energy_kwh", "emissions_kg", "idle_seconds"]].rename(columns={
                "datetime": "Date",
                "model_name": "Model",
                "stage": "Stage",
                "duration_s": "Duration (s)",
                "energy_kwh": "Energy (kWh)",
                "emissions_kg": "CO2 (kg)",
                "idle_seconds": "Idle (s)",
            }),
            use_container_width=True,
            hide_index=True,
        )

        st.markdown("**Energy over time**")
        st.line_chart(df.set_index("datetime")["energy_kwh"])

        st.markdown("**CO2 over time**")
        st.line_chart(df.set_index("datetime")["emissions_kg"])

        if st.button("Clear history"):
            history.clear()
            st.success("History cleared.")
            st.rerun()


elif page == "Security Report":
    st.markdown('<div class="section-title">Security Report</div>', unsafe_allow_html=True)
    st.markdown("""
GreenTensor monitors the GPU power draw continuously during training.
Anomalous patterns in the carbon footprint signal potential threats in the MLOps pipeline.

**Detection methods:**
- **alibi-detect SpectralResidual** — statistical frequency-domain analysis of the power time series. Flags points that deviate from the expected pattern, not just a fixed threshold.
- **Threshold detector** — fallback when alibi-detect is unavailable. Alerts when power exceeds baseline by a configurable percentage.
- **LLM Guard** — scans model inputs for prompt injection and secrets, and model outputs for sensitive data leakage.

**Threat types detected:**

| Threat | What it means |
|--------|---------------|
| `power_spike` | Sudden energy surge — possible cryptominer injected into the pipeline |
| `idle_drain` | GPU consuming power while idle — possible hidden background process or data exfiltration |
| `prompt_injection` | Adversarial input targeting the model — detected by LLM Guard |
| `data_leakage` | Sensitive data in model output — detected by LLM Guard |
    """)

    if not security_alerts:
        st.markdown('<div class="clean-badge">CLEAN — No threats detected in this session</div>', unsafe_allow_html=True)
        st.markdown("")
        st.markdown("Security alerts appear here automatically when GreenTensor detects anomalous energy patterns during a live training run.")
    else:
        st.markdown(f'<div class="threat-badge">THREATS DETECTED — {len(security_alerts)} alert(s)</div>', unsafe_allow_html=True)
        st.markdown("")
        for a in security_alerts:
            css = f"alert-{a.severity}"
            st.markdown(f"""
            <div class="{css}">
                <span class="tag tag-type">{a.alert_type.upper()}</span>
                <span class="tag tag-source">{a.source}</span>
                <strong>{a.severity.upper()}</strong><br>
                {a.message}
            </div>""", unsafe_allow_html=True)


elif page == "How It Works":
    st.markdown('<div class="section-title">How GreenTensor Works</div>', unsafe_allow_html=True)
    st.markdown("""
**What is GreenTensor?**

GreenTensor is a Python middleware package for PyTorch ML workloads.
It wraps your existing training code with one context manager and adds four capabilities
without requiring any changes to your model or training logic.

---

**Usage**

```python
from greentensor import GreenTensor

with GreenTensor() as gt:
    with gt.mixed_precision():
        train()   # your existing code, unchanged
```

---

**What happens inside the context manager**

When you enter `with GreenTensor()`:

1. GPU optimizer applies cuDNN benchmark mode and enables mixed precision (FP16).
   This reduces memory usage and speeds up matrix operations on CUDA GPUs.

2. Idle optimizer starts a background thread sampling GPU utilization every 0.5 seconds.
   If utilization drops below 10%, it records idle time to quantify wasted energy.

3. Anomaly detector starts a second background thread sampling GPU power draw every second.
   It builds a rolling baseline of normal power consumption and flags deviations.

4. CodeCarbon starts tracking carbon emissions using your region's grid carbon intensity.
   If CodeCarbon is unavailable, GreenTensor falls back to nvidia-smi power sampling.

When you exit the context:

5. All threads stop and measurements are collected.
6. A RunMetrics object is created with duration, energy, emissions, and idle time.
7. If a baseline RunMetrics was passed in, savings are calculated against real measured data.
8. A report is printed to the terminal.

---

**The file upload in this dashboard**

When you run `train_baseline.py` or `train_optimized.py`, GreenTensor saves a
`RunMetrics` object to a `.pkl` file using Python's pickle serialization.

That file contains exactly four values:
- `duration_s` — wall-clock time of the run
- `energy_kwh` — energy measured by CodeCarbon or nvidia-smi
- `emissions_kg` — CO2 calculated from energy and grid carbon intensity
- `idle_seconds` — time the GPU spent below the utilization threshold

When you upload that file here, the dashboard deserializes it back into a `RunMetrics`
object, computes the savings between baseline and optimized, and renders the charts.

You can also create a `.json` file manually with the same four fields if you want to
enter data from an external source or a different tool.

---

**Security monitoring**

The anomaly detector uses the SpectralResidual algorithm from alibi-detect (Apache 2.0).
This is the same algorithm Microsoft uses in Azure Metrics Advisor for production anomaly detection.

It works by computing the Fourier transform of the power time series, removing the
expected frequency components, and flagging residuals that exceed a threshold.
This catches subtle, sustained anomalies that a simple threshold would miss.

LLM Guard (MIT, by Protect AI) adds a second layer by scanning model inputs and outputs
for prompt injection patterns, leaked secrets, and sensitive data.

Install the full security stack with:
```bash
pip install greentensor[security]
```
    """)
