# -*- coding: utf-8 -*-
"""
AquaTensor Integration — Water Intelligence Layer for GreenTensor.

Connects AI compute telemetry to AquaTensor's membrane distillation system.

The physics:
  Every watt of GPU compute becomes waste heat.
  Membrane distillation uses that heat (40-80 C) to produce fresh water.
  GreenTensor measures the compute, predicts the heat, forecasts water yield,
  and optimizes scheduling to maximize AquaTensor's water production.

Key metrics:
  WUE  — Water Usage Effectiveness (liters consumed per kWh of IT load)
  WHR  — Waste Heat Recovery ratio (fraction of heat captured by AquaTensor)
  MD efficiency — Membrane Distillation yield (liters water per kWh thermal)
  WPI  — Water Productivity Index (liters produced per kWh of compute)
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict
import time
import math


# ── Published WUE coefficients by cloud provider ──────────────────────────────
# Source: provider sustainability reports (2023-2024)
PROVIDER_WUE = {
    "google":        0.49,   # Google 2023 Environmental Report
    "microsoft":     0.49,   # Microsoft 2023 Sustainability Report
    "aws":           1.80,   # Industry estimate (AWS does not publish WUE)
    "meta":          0.26,   # Meta 2023 Sustainability Report
    "oracle":        1.20,   # Oracle Cloud Infrastructure estimate
    "on_premise":    1.80,   # ASHRAE industry average
    "custom":        None,
}

# Membrane distillation yield by feed temperature
# Source: Khayet & Matsuura, Membrane Distillation (2011)
# liters of fresh water per kWh of thermal energy
MD_YIELD_BY_TEMP = {
    40: 2.5,   # minimum viable temperature
    50: 4.0,   # typical datacenter exhaust air
    60: 5.5,   # typical liquid cooling return
    70: 7.0,   # high-efficiency liquid cooling
    80: 8.5,   # maximum practical for MD
}

# Regional water stress index (0-5 scale, World Resources Institute Aqueduct)
# Higher = more water stressed
REGIONAL_WATER_STRESS = {
    "US-West":      4.2,   # California, Nevada — extremely high stress
    "US-East":      1.8,   # Virginia, Ohio — medium stress
    "US-Central":   2.1,   # Texas — high stress
    "EU-West":      2.3,   # Ireland, Netherlands — medium
    "EU-South":     3.8,   # Spain, Italy — high stress
    "India":        4.5,   # extremely high stress
    "Singapore":    3.1,   # high stress
    "Australia":    3.6,   # high stress
    "Norway":       0.8,   # low stress (hydro-rich)
    "Canada":       1.2,   # low stress
    "default":      2.5,   # world average
}


@dataclass
class AquaTensorConfig:
    """
    Configuration for the AquaTensor membrane distillation system
    connected to this datacenter.
    """
    # Datacenter / cloud provider
    provider: str = "on_premise"          # key from PROVIDER_WUE
    custom_wue: Optional[float] = None    # override if provider="custom"
    region: str = "default"               # key from REGIONAL_WATER_STRESS

    # AquaTensor hardware parameters
    aquatensor_installed: bool = False    # True if AquaTensor MD system is present
    whr_ratio: float = 0.65              # Waste Heat Recovery ratio (0-1)
                                          # fraction of GPU heat captured by AquaTensor
    feed_temperature_c: float = 60.0     # coolant temperature fed to MD membrane
    membrane_area_m2: float = 10.0       # total membrane area in m2
    custom_md_yield: Optional[float] = None  # override MD yield liters/kWh

    # Scheduling thresholds for water optimization
    min_temp_for_md: float = 40.0        # below this, MD stops producing
    optimal_temp_range: tuple = (55.0, 75.0)  # optimal MD operating range


@dataclass
class WaterMetrics:
    """Water consumption and production metrics for one compute session."""
    duration_s: float
    energy_kwh: float

    # Consumption side (traditional cooling)
    wue: float                            # liters per kWh
    water_consumed_liters: float          # water evaporated for cooling

    # Production side (AquaTensor recovery)
    aquatensor_installed: bool
    heat_generated_kwh: float             # same as energy_kwh (conservation of energy)
    heat_recovered_kwh: float             # heat captured by AquaTensor
    feed_temperature_c: float
    md_yield_liters_per_kwh: float        # membrane distillation efficiency
    water_produced_liters: float          # fresh water generated by AquaTensor
    net_water_impact_liters: float        # consumed - produced (negative = net positive)

    # Context
    region: str
    water_stress_index: float
    water_stress_label: str

    # Equivalencies
    drinking_water_days: float            # how many person-days of drinking water produced
    water_saved_vs_traditional: float     # liters saved vs traditional cooling

    @property
    def is_net_water_positive(self) -> bool:
        return self.net_water_impact_liters < 0


@dataclass
class HeatForecast:
    """Predicted heat output and water yield for upcoming compute jobs."""
    forecast_horizon_hours: float
    predicted_energy_kwh: float
    predicted_heat_kwh: float
    predicted_water_liters: float
    optimal_schedule_recommendation: str
    temperature_sustained: bool           # will heat stay above MD minimum?


class AquaTensorBridge:
    """
    The intelligence layer connecting GreenTensor compute telemetry
    to AquaTensor's membrane distillation system.

    Responsibilities:
    1. Calculate water consumption from real measured energy
    2. Calculate water production from waste heat recovery
    3. Forecast heat output for upcoming jobs
    4. Optimize compute scheduling for maximum water yield
    5. Report net water impact per AI workload
    """

    def __init__(self, config: AquaTensorConfig = None):
        self.config = config or AquaTensorConfig()
        self._power_samples: List[float] = []
        self._sample_times: List[float] = []

    # ── Core calculation ───────────────────────────────────────────────────────

    def calculate_water_metrics(self, energy_kwh: float, duration_s: float) -> WaterMetrics:
        """
        Given real measured energy consumption, calculate full water metrics.

        Parameters
        ----------
        energy_kwh  : real measured energy from GreenTensor tracker
        duration_s  : session duration in seconds
        """
        # Water consumption (traditional cooling)
        wue = self._get_wue()
        water_consumed = energy_kwh * wue

        # Heat generated = energy consumed (conservation of energy)
        heat_generated_kwh = energy_kwh

        # Heat recovered by AquaTensor
        heat_recovered_kwh = heat_generated_kwh * self.config.whr_ratio if self.config.aquatensor_installed else 0.0

        # MD yield based on feed temperature
        md_yield = self.config.custom_md_yield or self._get_md_yield(self.config.feed_temperature_c)

        # Water produced
        water_produced = heat_recovered_kwh * md_yield if self.config.aquatensor_installed else 0.0

        # Net impact
        net_impact = water_consumed - water_produced

        # Context
        stress_index = REGIONAL_WATER_STRESS.get(self.config.region,
                       REGIONAL_WATER_STRESS["default"])
        stress_label = self._stress_label(stress_index)

        # Equivalencies
        # Average person drinks 2 liters/day
        drinking_days = water_produced / 2.0
        # Traditional cooling would have consumed water_consumed liters
        # AquaTensor recovers water_produced liters back
        water_saved = water_produced  # every liter produced is a liter not drawn from municipal supply

        return WaterMetrics(
            duration_s=duration_s,
            energy_kwh=energy_kwh,
            wue=wue,
            water_consumed_liters=water_consumed,
            aquatensor_installed=self.config.aquatensor_installed,
            heat_generated_kwh=heat_generated_kwh,
            heat_recovered_kwh=heat_recovered_kwh,
            feed_temperature_c=self.config.feed_temperature_c,
            md_yield_liters_per_kwh=md_yield,
            water_produced_liters=water_produced,
            net_water_impact_liters=net_impact,
            region=self.config.region,
            water_stress_index=stress_index,
            water_stress_label=stress_label,
            drinking_water_days=drinking_days,
            water_saved_vs_traditional=water_saved,
        )

    def forecast_heat(self, queued_jobs: List[Dict]) -> HeatForecast:
        """
        Predict heat output and water yield for a queue of upcoming jobs.

        Parameters
        ----------
        queued_jobs : list of dicts with keys:
                      'name', 'estimated_duration_s', 'estimated_power_w'
        """
        total_energy = sum(
            (j.get("estimated_power_w", 200) * j.get("estimated_duration_s", 3600)) / 3_600_000
            for j in queued_jobs
        )
        total_hours = sum(j.get("estimated_duration_s", 3600) for j in queued_jobs) / 3600

        md_yield = self.config.custom_md_yield or self._get_md_yield(self.config.feed_temperature_c)
        heat_recovered = total_energy * self.config.whr_ratio
        water_predicted = heat_recovered * md_yield if self.config.aquatensor_installed else 0.0

        temp_sustained = self.config.feed_temperature_c >= self.config.min_temp_for_md

        # Scheduling recommendation
        if not temp_sustained:
            rec = (f"WARNING: Feed temperature {self.config.feed_temperature_c}C is below "
                   f"MD minimum {self.config.min_temp_for_md}C. "
                   f"Consolidate jobs to maintain heat above threshold.")
        elif self.config.feed_temperature_c < self.config.optimal_temp_range[0]:
            rec = (f"Schedule jobs continuously to maintain temperature above "
                   f"{self.config.optimal_temp_range[0]}C for optimal MD yield.")
        else:
            rec = (f"Current schedule will sustain {self.config.feed_temperature_c}C — "
                   f"optimal for membrane distillation. Predicted yield: {water_predicted:.1f}L.")

        return HeatForecast(
            forecast_horizon_hours=total_hours,
            predicted_energy_kwh=total_energy,
            predicted_heat_kwh=heat_recovered,
            predicted_water_liters=water_predicted,
            optimal_schedule_recommendation=rec,
            temperature_sustained=temp_sustained,
        )

    def record_power_sample(self, power_w: float):
        """Record a real-time power sample for heat curve tracking."""
        self._power_samples.append(power_w)
        self._sample_times.append(time.time())
        if len(self._power_samples) > 3600:  # keep 1 hour of samples
            self._power_samples = self._power_samples[-3600:]
            self._sample_times = self._sample_times[-3600:]

    def current_heat_rate_w(self) -> float:
        """Current heat generation rate in watts (= current GPU power draw)."""
        if self._power_samples:
            return self._power_samples[-1]
        return 0.0

    def is_md_viable(self) -> bool:
        """Is the current temperature sufficient for membrane distillation?"""
        return self.config.feed_temperature_c >= self.config.min_temp_for_md

    # ── Helpers ────────────────────────────────────────────────────────────────

    def _get_wue(self) -> float:
        if self.config.provider == "custom" and self.config.custom_wue:
            return self.config.custom_wue
        return PROVIDER_WUE.get(self.config.provider, PROVIDER_WUE["on_premise"])

    def _get_md_yield(self, temp_c: float) -> float:
        """Interpolate MD yield from temperature lookup table."""
        temps = sorted(MD_YIELD_BY_TEMP.keys())
        if temp_c <= temps[0]:
            return MD_YIELD_BY_TEMP[temps[0]]
        if temp_c >= temps[-1]:
            return MD_YIELD_BY_TEMP[temps[-1]]
        for i in range(len(temps) - 1):
            if temps[i] <= temp_c <= temps[i + 1]:
                t0, t1 = temps[i], temps[i + 1]
                y0, y1 = MD_YIELD_BY_TEMP[t0], MD_YIELD_BY_TEMP[t1]
                return y0 + (y1 - y0) * (temp_c - t0) / (t1 - t0)
        return MD_YIELD_BY_TEMP[60]

    @staticmethod
    def _stress_label(index: float) -> str:
        if index < 1.0:   return "Low"
        if index < 2.0:   return "Low-Medium"
        if index < 3.0:   return "Medium-High"
        if index < 4.0:   return "High"
        return "Extremely High"
